### ISSUE TITLE
Script of rasqualToEigenMT

### ISSUE THREAD

**Issue by hbliu** [kauralasoo/macrophage-gxe-study#2]
Hi Kaur,

I am trying to use EigenMT to eQTL mapped by rasqual.
I am wondering where can I find the code (rasqualToEigenMT.py) converting rasqual output to EigenMT input?

Thank you,
Hongbo

**Comment by kauralasoo** [comment]
Hi Hongbo,

The script is here: https://github.com/kauralasoo/rasqual/blob/master/scripts/rasqualToEigenMT.py

Please note that I have not touched it in seven years and will not be able to help you if it does not work.

Best,
Kaur

**Comment by hbliu** [comment]
> 

Hi Kaur,

Thank you so much for sharing the code!

Hongbo
